Add initial CodeChecker support and fix first CodeChecker warning.

diff --git a/.github/workflows/pr_build.yml b/.github/workflows/pr_build.yml
--- a/.github/workflows/pr_build.yml
+++ b/.github/workflows/pr_build.yml
@@ -22,8 +22,6 @@ env:
   UPLOAD_REGION: fra1
   UPLOAD_ENDPOINT: "https://fra1.digitaloceanspaces.com"
 
-  CMAKE_BUILD_EXTRA: --preset conan-release
-
 jobs:
   build_pr:
     name: "${{matrix.os}}, ${{matrix.arch}}"
@@ -41,14 +39,14 @@ jobs:
             #  build_type: full
             #  qt_source: aqt
             - os: Ubuntu 22.04 OpenGL
-              image: docker.io/overte/overte-full-build:2026-05-05-ubuntu-22.04-amd64  # Container image used for building. Built from /tools/ci-script/linux-ci/Dockerfile_x
+              image: docker.io/overte/overte-full-build:2026-06-12-ubuntu-22.04-amd64  # Container image used for building. Built from /tools/ci-script/linux-ci/Dockerfile_x
               runner: ubuntu-latest
               arch: amd64
               build_type: full
               qt_source: system
               rendering_backend: OpenGL
             - os: Ubuntu 22.04 Vulkan
-              image: docker.io/overte/overte-full-build:2026-05-05-ubuntu-22.04-amd64
+              image: docker.io/overte/overte-full-build:2026-06-12-ubuntu-22.04-amd64
               runner: ubuntu-latest
               arch: amd64
               build_type: full
@@ -60,19 +58,26 @@ jobs:
             #  apt-dependencies: mesa-common-dev libegl1 libglvnd-dev libdouble-conversion1 libpulse0 python3-github python3-distro
             # Do not change the names of self-hosted runners without knowing what you are doing, as they correspond to labels that have to be set on the runner.
             - os: Ubuntu 22.04 OpenGL
-              image: docker.io/overte/overte-full-build:2026-05-05-ubuntu-22.04-aarch64
+              image: docker.io/overte/overte-full-build:2026-06-12-ubuntu-22.04-aarch64
               runner: ubuntu-24.04-arm
               arch: aarch64
               build_type: full
               qt_source: system
               rendering_backend: OpenGL
             - os: Ubuntu 22.04 Vulkan
-              image: docker.io/overte/overte-full-build:2026-05-05-ubuntu-22.04-aarch64
+              image: docker.io/overte/overte-full-build:2026-06-12-ubuntu-22.04-aarch64
               runner: ubuntu-24.04-arm
               arch: aarch64
               build_type: full
               qt_source: system
               rendering_backend: Vulkan
+            - os: Ubuntu 22.04 CodeChecker
+              image: docker.io/overte/overte-full-build:2026-06-12-ubuntu-22.04-amd64
+              runner: depot-ubuntu-24.04-16
+              arch: amd64
+              build_type: CodeChecker
+              qt_source: system
+              rendering_backend: OpenGL
         fail-fast: false
     runs-on: ${{matrix.runner}}
     container: ${{matrix.image}}
@@ -99,6 +104,8 @@ jobs:
       shell: bash
       id: buildenv1
       run: |
+        # Work around https://github.com/actions/runner/issues/2058
+        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
 
         # Setting short commit SHA for use as RELEASE_NAME in generated installers.
         echo "GIT_COMMIT_SHORT=`echo $GIT_COMMIT | cut -c1-7`" >> $GITHUB_ENV
@@ -120,6 +127,12 @@ jobs:
             fi
           fi
         fi
+
+        if [[ "${{ matrix.os }}" =~ "CodeChecker" ]]; then
+            # Override CMake BUILD_TYPE
+            echo "BUILD_TYPE=Debug" >> $GITHUB_ENV
+        fi
+
         # Mac build variables
         if [ "${{ matrix.os }}" = "macOS-10.15" ]; then
           if [ "${{ matrix.build_type }}" = "full" ]; then
@@ -200,32 +213,90 @@ jobs:
           cmake --preset conan-${BUILD_TYPE,,} -DOVERTE_RELEASE_NUMBER=${{ github.event.number }} -DOVERTE_GIT_COMMIT_SHORT=$GIT_COMMIT_SHORT -DOVERTE_RELEASE_TYPE=PR $CMAKE_EXTRA
         fi
 
+    - name: Run CodeChecker static analysis
+      # TODO: Use upstream action once all changes are upstreamed.
+      uses: JulianGro/CodeChecker-Action@v1.0.4-overte
+      if: matrix.build_type == 'CodeChecker'
+      id: codechecker
+      with:
+        build-command: cmake --build --preset conan-debug --target codegen
+        skipfile: ${{ env.GITHUB_WORKSPACE }}/.github/codechecker/skipfile.txt
+        # Allow static analyzers to analyze across files instead of one file at a time.
+        # TODO: Enable CTU after refactor. If we enable it now, we will always introduce new warnings, since the baseline doesn't get updated.
+        #ctu: true
+
+        # Update CodeChecker master branch results.
+        # TODO: Refactor our GitHub Actions workflows to put master, PR, and release builds in one workflow.
+        store: ${{ github.event_name == 'push' }}
+        store-url: "https://codechecker.overte.org/overte"
+        store-username: ${{ secrets.CODECHECKER_STORE_USER }}
+        store-password: ${{ secrets.CODECHECKER_STORE_PASSWORD }}
+        # Use clang and clang-tidy from our Docker image.
+        llvm-version: "ignore"
+        # Use the same CodeChecker versions as installed in the Docker image.
+        version: "6.28.0"
+        store-run-name: "main"
+
+        # Compare Pull Request against master branch, to see if there are any new warnings.
+        diff: ${{ github.event_name == 'pull_request' }}
+        diff-url: 'https://codechecker.overte.org/overte'
+        # We cannot use secrets on Pull Requests, so we use a separate read-only account.
+        diff-username: github_actions_read
+        diff-password: "xDylatsf@3Jcyz$"
+        # Which result to compare against.
+        diff-run-name: "main"
+
+    - name: Upload CodeChecker analysis warnings
+      uses: actions/upload-artifact@v7
+      if: matrix.build_type == 'CodeChecker'
+      with:
+        name: "CodeChecker analysis warnings.zip"
+        path: ${{ steps.codechecker.outputs.result-html-dir }}
+        if-no-files-found: error
+
+    # Upload the potential new findings results to the CI.
+    - name: Upload new CodeChecker analysis warnings
+      uses: actions/upload-artifact@v7
+      if: ${{ steps.codechecker.outputs.warnings-in-diff == 'true' }}
+      with:
+        name: "Newly introduced analysis warnings.zip"
+        path: ${{ steps.codechecker.outputs.diff-html-dir }}
+        if-no-files-found: error
+
+    - name: "Fail the job if new findings are introduced"
+      if: ${{ steps.codechecker.outputs.warnings-in-diff == 'true' }}
+      shell: bash
+      run: |
+        echo "::error title=New static analysis warnings::Analysed commit would introduce new static analysis warnings and potential bugs to the project."
+        # Fail the build, after results were collected and uploaded.
+        exit 1
+
     - name: Build Application
       if: matrix.build_type == 'full' || matrix.build_type == 'client'
       shell: bash
-      run: cmake --build --target $APP_TARGET_NAME $CMAKE_BUILD_EXTRA
+      run: cmake --build --target $APP_TARGET_NAME --preset conan-${BUILD_TYPE,,}
 
     - name: Build Domain Server
       if: matrix.build_type == 'full'
       shell: bash
-      run: cmake --build --target domain-server $CMAKE_BUILD_EXTRA
+      run: cmake --build --target domain-server --preset conan-${BUILD_TYPE,,}
 
     - name: Build Assignment Client
       if: matrix.build_type == 'full'
       shell: bash
-      run: cmake --build --target assignment-client $CMAKE_BUILD_EXTRA
+      run: cmake --build --target assignment-client --preset conan-${BUILD_TYPE,,}
 
     - name: Build Console
       if: matrix.build_type == 'full' && matrix.arch != 'aarch64' || startsWith(matrix.os, 'windows')
       shell: bash
       run: |
-        cmake --build --target packaged-server-console $CMAKE_BUILD_EXTRA
+        cmake --build --target packaged-server-console --preset conan-${BUILD_TYPE,,}
 
     - name: Build Installer
       if: matrix.build_type != 'android'
       shell: bash
       run: |
-        cmake --build --config $BUILD_TYPE --target package $CMAKE_BUILD_EXTRA
+        cmake --build --config $BUILD_TYPE --target package --preset conan-${BUILD_TYPE,,}
         rm build/Overte-*.json || true  # Remove JSON created by CPack External Generator to avoid it landing in the CI Artifacts.
 
     # As of 05/17/21 GitHub Virtual Environments changed their "Ubuntu 18.04.5 LTS" image to include two versions of CMake for Android
